name: 'retail'
profile: 'retail'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail:
    materialized: table

seeds:
  retail:
    +schema: raw
    online_retail:
      +column_types:
        InvoiceNo: varchar
        StockCode: varchar
        Description: varchar
        Quantity: int
        InvoiceDate: varchar
        UnitPrice: double
        CustomerID: varchar
        Country: varchar
    country:
      +column_types:
        id: int
        iso: varchar
        name: varchar
        nicename: varchar
        iso3: varchar
        numcode: varchar
        phonecode: int
